### ISSUE TITLE
Use flexvolume based notation for raw/qcow2 volumes

### ISSUE THREAD

**Issue by ivan4th** [Mirantis/virtlet#286]
This is required by Stage 3 of Virtlet [cloud-init metadata generation proposal](https://github.com/Mirantis/virtlet/blob/master/docs/design-proposals/cloud-init-data-generation.md)

The volume handling in Virtlet needs to be consistent so the volumes can be defined like this:
```yaml
  volumes:
  - name: config
    configMap:
      name: someconfig
  - name: secret
    secret:
      secretName: somesecret
  - name: extra
    flexVolume:
      driver: "virtlet/flexvolume_driver"
      options:
        type: qcow2
        capacity: 2048MiB
  - name: raw
    flexVolume:
      driver: "virtlet/flexvolume_driver"
      options:
        type: raw
        path: /dev/mapper/somevg
  - name: ceph
    flexVolume:
      driver: "virtlet/flexvolume_driver"
      options:
        type: ceph
        monitor: 10.0.0.1:6789
        user: libvirt
        secret: ....
        volume: rbd-test-image
        pool: libvirt-pool
```
Of these, ceph flexvolume already works like above, but we need raw/qcow2 volumes to work like this, too.
