### ISSUE TITLE
Support mounting virtlet flexvolumes using volumeMounts

### ISSUE THREAD

**Issue by ivan4th** [Mirantis/virtlet#287]
This is Stage 3 of Virtlet [cloud-init data generation proposal](https://github.com/Mirantis/virtlet/blob/master/docs/design-proposals/cloud-init-data-generation.md). It depends on #286 

Virtlet should generate cloud-init user-data that mounts virtlet flexvolumes into the VM.
E.g. the following should cause the corresponding volumes to be mounted under
`/var/lib/docker`, `/var/lib/postgresql` and `/cephdata`:

```yaml
  containers:
  - name: ubuntu-vm
    image: virtlet/cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-disk1.img
    volumeMounts:

    # mount the qcow2 volume under /var/lib/docker
    - name: extra
      mountPath: /var/lib/docker

    # mount a raw device under /var/lib/postgresql
    - name: raw
      mountPath: /var/lib/postgresql

    # mount a ceph volume under /cephdata
    - name: ceph
      mountPath: /cephdata

  volumes:
  - name: extra
    flexVolume:
      driver: "virtlet/flexvolume_driver"
      options:
        type: qcow2
        capacity: 2048MiB
  - name: raw
    flexVolume:
      driver: "virtlet/flexvolume_driver"
      options:
        type: raw
        path: /dev/mapper/somevg
  - name: ceph
    flexVolume:
      driver: "virtlet/flexvolume_driver"
      options:
        type: ceph
        monitor: 10.0.0.1:6789
        user: libvirt
        secret: ....
        volume: rbd-test-image
        pool: libvirt-pool
```

This is done by generating the following `mounts` section in `user-data`:
```yaml
#cloud-config
mounts:
- [ /dev/vdc1, /var/lib/docker ]
- [ /dev/vdd, /var/lib/postgresql ]
- [ /dev/vde, /cephdata ]
```
