### ISSUE TITLE
Consuming Secrets and ConfigMaps in Virtlet pods

### ISSUE THREAD

**Issue by ivan4th** [Mirantis/virtlet#289]
This is Stage 2 of Virtlet [cloud-init data generation proposal](https://github.com/Mirantis/virtlet/blob/master/docs/design-proposals/cloud-init-data-generation.md)

Implement applying the data from ConfigMap and Secret k8s objects via the write_files module in user-data. Possible additional option is to generate a shell script to serve as user-data so CirrOS and other images with 'simpler' cloud-init can be supported, too. Possible problem: user-data is usually limited to ~16Kb by cloud providers, need to check whether this limitation isn't enforced by any images on the OS side.

An excerpt from pod definition:
```yaml
  containers:
  - name: ubuntu-vm
    image: virtlet/cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-disk1.img
    volumeMounts:

    # this will write configmap contents using the `write_file` cloud-init module
    - name: config
      mountPath: /etc/foobar

    # this will write secret contents using the `write_file` cloud-init module
    - name: secret
      mountPath: /etc/baz
volumes:
  - name: config
    configMap:
      name: someconfig
  - name: secret
    secret:
      secretName: somesecret
```

This produces the following `write_files` instructions in user-data:
```yaml
write_files:
- path: /etc/foobar/some-file-from-configmap.conf
  permissions: '0644'
  encoding: b64
  content: IyB0aGlzIGlzIGEgc2FtcGxlIGNvbmZpZyBmaWxlCiMgdGFrZW4gZnJvbSBhIGNvbmZpZ21hcAo=
- path: /etc/baz/a-file-taken-from-secrets.conf
  permissions: '0600'
  encoding: b64
  content: IyBzb21lIHNlY3JldCBjb250ZW50Cg==
```
