### ISSUE TITLE
Retrieving parts of cloud-init configuration from Secrets and ConfigMaps

### ISSUE THREAD

**Issue by ivan4th** [Mirantis/virtlet#290]
This is Stage 4 of Virtlet [cloud-init data generation proposal](https://github.com/Mirantis/virtlet/blob/master/docs/design-proposals/cloud-init-data-generation.md)

Implement retrieving parts of cloud-init configuration from Secrets and ConfigMaps. This includes retrieving SSH public keys from Secrets/ConfigMaps specified using `VirtletSSHKeySource` (this part also needs to be done because it's not very correct to embed SSH keys into pod definitions). Also implement retrieving cloud-init user-data overrides from Secrets/ConfigMaps specified using `VirtletCloudInitUserDataSource`.

Sample annotations:
```yaml
    # it's also possible to use a configmap or a secret to override
    # parts of user-data (you may use secret/ instead of configmap/ below)
    VirtletCloudInitUserDataSource: configmap/vm-user-data

    # ssh keys may also be pulled from 'authorized_keys' key
    # in a ConfigMap or a Secret
    VirtletSSHKeySource: secret/mysecret
    # can also use the following:
    # VirtletSSHKeySource: configmap/configmap-with-public-keys
```

`VirtletCloudInitUserDataSource` causes the keys of a ConfigMap or a Secret it points to to be merged with the generated cloud-init user-data using standard cloud-init [user-data merge algorithm](VirtletCloudInitUserDataSource) (unless it's disabled using `VirtletCloudInitUserDataOverwrite: true` annotation). During the merge, the autogenerated user-data comes first, then the contents of `VirtletCloudInitUserData` and finally the data taken from a Secret or ConfigMap specified via `VirtletCloudInitUserDataSource`.

`VirtletSSHKeySource` makes it possible to take ssh public keys from `authorized_keys` key of a Secret or ConfigMap.

This issue requires access to apiserver from Virtlet pod, so `ClusterRole` spec for Virtlet will need to be updated, too.
