### ISSUE TITLE
Continuous logging

### ISSUE THREAD

**Issue by miha-plesko** [Mirantis/virtlet#310]
I'm opening this as an issue although it's actually an anti-issue as you will see 😄 It was mentioned on Slack channel that there is a problem when following VM logs continuously using `kubeclt logs -f <VM>`. However, in my local environment everything seems to be working as expected.

### How did I test
Deploy a container and a VM that both write to stdout every second:
```bash
$ kubectl create -f printer-container.yaml
$ kubectl create -f printer-vm.yaml
```
Where printer-container.yaml has the follwong content:
```yaml
# printer-container.yaml

apiVersion: v1
kind: Pod
metadata:
  name: printer-container
spec:
  containers:
  - name: printer-container
    image: busybox
    args: [/bin/sh, -c,
            'i=0; while true; do echo "$i: $(date)"; i=$((i+1)); sleep 1; done']
```
and printer-vm.yaml has the follwong content:
```yaml
# printer-vm.yaml

apiVersion: v1
kind: Pod
metadata:
  name: printer-vm
  annotations:
    kubernetes.io/target-runtime: virtlet
    VirtletVCPUCount: "1"
    VirtletSSHKeys: |
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCaJEcFDXEK2ZbX0ZLS1EIYFZRbDAcRfuVjpstSc0De8+sV1aiu+dePxdkuDRwqFtCyk6dEZkssjOkBXtri00MECLkir6FcH3kKOJtbJ6vy3uaJc9w1ERo+wyl6SkAh/+JTJkp7QRXj8oylW5E20LsbnA/dIwWzAF51PPwF7A7FtNg9DnwPqMkxFo1Th/buOMKbP5ZA1mmNNtmzbMpMfJATvVyiv3ccsSJKOiyQr6UG+j7sc/7jMVz5Xk34Vd0l8GwcB0334MchHckmqDB142h/NCWTr8oLakDNvkfC1YneAfAO41hDkUbxPtVBG5M/o7P4fxoqiHEX+ZLfRxDtHB53 me@localhost
    VirtletCloudInitUserDataScript: |
      #!/bin/sh
      echo "Hi there"
      i=0
      while true; do
        echo "$i: Hello"
        i=$((i+1))
        sleep 1
      done
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: extraRuntime
            operator: In
            values:
            - virtlet
  containers:
  - name: printer-vm
    image: virtlet/download.cirros-cloud.net/0.3.5/cirros-0.3.5-x86_64-disk.img
    resources:
      limits:
        memory: 128Mi
```
As far as it concerns logging, the two pods behave identically:

* If I run `kubeclt logs -f printer-container` it continuously prints me the container output. Also if I run `kubectl logs -f printer-vm` it continously prints me the VM output.
* If I visit "Logs" tab of printer-container on Kubernetes Dashboard, I see current logs, but they do not update automatically (I need to press F5 to see newer ones). The same goes for printer-vm "Logs" tab.

@ivan4th do you observe different behavior?

/cc @gberginc
