### ISSUE TITLE
Image name translation in Virtlet p.1

### ISSUE THREAD

**Issue by ivan4th** [Mirantis/virtlet#400]
There are several problems with Virtlet image handling:
1. Docker image name restrictions are imposed on image names, thus it's impossible to have image names with uppercase letters for example
2. It's only possible to use HTTP or HTTPS but not both at the same time, i.e. it's not possible to download some images over HTTP (e.g. from a simple local image server) and some over HTTPS (e.g. from some web site).
3. Web server name is hardwired in k8s object definition, so it's necessary to modify the object with jq/sed/etc. if the web server is not accessible from the particular k8s node at the moment of container startup (e.g. because of network isolation, temporary web server issues etc.)

The suggestion is to provide a yaml config file for Virtlet that describes image name translations. In a followup task, the file will be replaced by a Custom Resource Definition (CRD, formely Third Party Resource, TPR). The file has the following format:
```yaml
- name: cirros/current
  url: https://download.cirros-cloud.net/0.3.5/cirros-0.3.5-x86_64-disk.img
- name: ubuntu/16.04
  url: https://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-disk1.img
- name: cirros/local
  url: http://image-service.default.svc.cluster.local/cirros-0.3.5-x86_64-disk.img
- regexp: 'cirros/(\d+\.\d+\.\d+)'
  url: 'https://download.cirros-cloud.net/$1/cirros-$1-x86_64-disk.img'
- regexp: 'centos/(\d+)-(\d+)'
  url: 'https://cloud.centos.org/centos/$1/images/CentOS-$1-x86_64-GenericCloud-$2.qcow2'
```
`name` entries here specify the direct correspondence, so e.g. `virtlet/cirros/current` will refer to `https://download.cirros-cloud.net/0.3.5/cirros-0.3.5-x86_64-disk.img` (`virtlet/` prefix is still necessary because the translation happens "below" CRI proxy level).
`regexp` entries make it possible to match the image name against a regexp and then reuse submatches to construct the image name
(`$N` submatch refs are handled by Go's `Regexp.ReplaceAll()`). For example, in case of last entry it's possible to translate `virtlet/centos/7-1707` to `https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud-1707.qcow2` and `virtlet/centos/6-1510` to `https://cloud.centos.org/centos/6/images/CentOS-6-x86_64-GenericCloud-1510.qcow2`. Note that in the latter case we work around uppercase char problem while keeping some freedom in specifying different image versions.
