### ISSUE TITLE
Image name translation in Virtlet p.2

### ISSUE THREAD

**Issue by ivan4th** [Mirantis/virtlet#401]
This is a followup for #400.

Instead of using config file, Virtlet should read image name translation config from [CRDs](https://kubernetes.io/docs/tasks/access-kubernetes-api/extend-api-custom-resource-definitions/) (Custom Resource Definitions). The CRDs should be of kind `VirtletImageMapping`. All the CRDs of this kind are used, and any changes in these objects as well as adding new ones / deleting some of the CRDs should take effect immediately without the need to restart Virtlet pods.

Below is an example of a CRD:
```yaml
apiVersion: "virtlet.k8s/v1"
kind: VirtletImageMapping
metadata:
  name: primary
spec:
  translations:
  - name: cirros/current
    url: https://download.cirros-cloud.net/0.3.5/cirros-0.3.5-x86_64-disk.img
  - name: ubuntu/16.04
    url: https://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-disk1.img
  - name: cirros/local
    url: http://image-service.default.svc.cluster.local/cirros-0.3.5-x86_64-disk.img
  - regexp: 'cirros/(\d+\.\d+\.\d+)'
    url: 'https://download.cirros-cloud.net/$1/cirros-$1-x86_64-disk.img'
  - regexp: 'centos/(\d+)-(\d+)'
    url: 'https://cloud.centos.org/centos/$1/images/CentOS-$1-x86_64-GenericCloud-$2.qcow2'
```
