### ISSUE TITLE
ConfigMap `virtlet-config.download_protocol` not respected

### ISSUE THREAD

**Issue by miha-plesko** [Mirantis/virtlet#407]
I'm trying to deploy a VM on Virtlet by using the `imageserver` Pod. I've pulled latest Virtlet master and spinned cluster with:

```bash
$ ./deploy/demo.sh
```

Then I upload my VM image to the imageserver Pod and deploy it on Virtlet using following Deployment:

```yaml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: micro-keyvaluestore
spec:
  replicas: 1
  template:
    metadata:
      name: micro-keyvaluestore
      labels:
        case: micro-keyvaluestore
      annotations:
        kubernetes.io/target-runtime: virtlet
    spec:
      affinity: {"nodeAffinity": {"requiredDuringSchedulingIgnoredDuringExecution": {"nodeSelectorTerms": [{"matchExpressions": [{"key": "extraRuntime", "operator": "In", "values": ["virtlet"]}]}]}}}
      containers:
        - name: micro-keyvaluestore
          image: virtlet/image-service.kube-system/micro-keyvaluestore.qemu
          resources:
            limits:
              memory: 1024Mi
          ports:
          - name: app-port
            containerPort: 9000
```

But Pod fails to deploy with error:

```
Failed to pull image "virtlet/image-service.kube-system/micro-keyvaluestore.qemu": rpc error: code = 2
desc = "/run/virtlet.sock": rpc error: code = 2 desc = 
Get https://image-service.kube-system/micro-keyvaluestore.qemu: 
dial tcp 10.105.138.153:443: getsockopt: no route to host
Error syncing pod
```

Obviously, Virtlet attempts to use HTTPS protocol and therefore fails. But as far as I understand, my Virtlet is supposed to be using HTTP, because `virtlet-config.download_protocol` is set to HTTP:

![capture](https://user-images.githubusercontent.com/8102426/30263302-b23ed5c6-96d4-11e7-8f41-9ee899fe38c4.PNG)

The ConfigMap was set by [demo.sh:256](https://github.com/Mirantis/virtlet/blob/master/deploy/demo.sh#L256). Is it me doing something wrong or is it a bug?

**Comment by jellonek** [comment]
Please verify cmdline of Virtlet process - is there required parameter? If not, you need to look deeper on virtlet daemonset definition, it should contain:
```yaml
        - name: VIRTLET_DOWNLOAD_PROTOCOL
          valueFrom:
            configMapKeyRef:
              name: virtlet-config
              key: download_protocol
              optional: true
```
