### ISSUE TITLE
VirtletSSHKeys does not play well with VirtletCloudInitUserData

### ISSUE THREAD

**Issue by miha-plesko** [Mirantis/virtlet#460]
If I deploy the ubuntu VM like this:

```bash
$ kubectl create -f examples/ubuntu-vm.yaml
```

Then following appears in VM's logs:

```
cloud-init[1500]: Cloud-init v. 0.7.9 running 'modules:final' at Tue, 10 Oct 2017 08:18:35 +0000. Up 59.52 seconds.
cloud-init[1500]: ci-info: no authorized ssh keys fingerprints found for user testuser.
cloud-init[1500]: Cloud-init v. 0.7.9 finished at Tue, 10 Oct 2017 08:18:35 +0000. Datasource DataSourceNoCloud [seed=/dev/sr0][dsmode=net].
```

and we are unable to connect to the VM since the SSH key seems NOT to be added to the list of authorized keys:

```bash
$ ./examples/vmssh.sh testuser@ubuntu-vm
Warning: Permanently added 'ubuntu-vm.default' (ECDSA) to the list of known hosts.
testuser@ubuntu-vm.default's password: 
```

BUT if we modify the ubuntu-vm.yaml so that we provide ssh key as part of the cloud-init data (and not via VirtletSSHKeys parameter):

```yaml
VirtletCloudInitUserData: |
      ssh_pwauth: True
      users:
      - name: testuser
        gecos: User
        primary-group: testuser
        groups: users
        lock_passwd: false
        passwd: "$6$rounds=4096$wPs4Hz4tfs$a8ssMnlvH.3GX88yxXKF2cKMlVULsnydoOKgkuStTErTq2dzKZiIx9R/pPWWh5JLxzoZEx7lsSX5T2jW5WISi1"
        sudo: ALL=(ALL) NOPASSWD:ALL
        ssh-authorized-keys:                     #<------ added
          - ssh-rsa AAAAB3NzaC1...
# VirtletSSHKeys: |                              #<------- commented-out
#   ssh-rsa AAAAB3NzaC1...
```

then it works like a charm:

```bash
$ ./examples/vmssh.sh testuser@ubuntu-vm
Warning: Permanently added 'ubuntu-vm.default' (ECDSA) to the list of known hosts.
Welcome to Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-96-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud

0 packages can be updated.
0 updates are security updates.


Last login: Tue Oct 10 08:40:42 2017 from 10.192.0.3
$
```

I haven't debugged any further why this happens, since the workaround is trivial, but I'm reporting the issue because at the very least the example should be updated so that it's working out of the box ;)
