### ISSUE TITLE
Question: Ways to inject extra files in the cloud-init config drive

### ISSUE THREAD

**Issue by ramukima** [Mirantis/virtlet#736]
Great work related to the cloud-init functionality. I have a quick question though.

I understand that using ConfigDrive type, my VM is attached with a config drive (CDROM) with following layout -

/openstack/latest/meta_data.json
/openstack/latest/user-data
/openstack/latest/network_data.json

Given that my VM image does not have support for standard cloud-init through a config-drive, is there a way I could indicate that the same content that is written to user-data under 'write_files', is also injected with its decoded base64 content under the root path of the CDROM drive ?

For example -

```
VirtletCloudInitImageType: configdrive
        VirtletCloudInitUserData: |
          write_files:
          - path: /bar.txt
            permissions: "0644"
            owner: root
            content: |
              my bar content
           - path: /foo/foo.txt
            permissions: "0644"
            owner: root
            content: |
              my foo content
```

Given above annotation, I am expecting the config-drive content to be -

/openstack/latest/meta_data.json
/openstack/latest/user-data
/openstack/latest/network_data.json
/bar.txt
/foo/foo.txt

Notice that the paths mentioned under write_files annotation are relative to the root folder in the config drive. In the example above, my VM will ignore all content under /openstack (because it has no cloud-init support), but will be able to read the content of bar.txt and foo/foo.txt ?

Is there any other better way to achieve this ?
